name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-lastest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: sau hi to sanjeev
        run: echo "hi sanjeev"
        